// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Cat(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: "Cat",
                      className: "text-xl"
                    }),
                JsxRuntime.jsx("img", {
                      className: "max-w-sm mx-auto mt-5",
                      alt: "a cat",
                      src: "https://media.giphy.com/media/7YCA4XbA0ArQuWEfqJ/giphy.gif"
                    })
              ]
            });
}

var make = Cat;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
