// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Cats(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: "cats",
                      className: "text-xl"
                    }),
                JsxRuntime.jsx("img", {
                      className: "max-w-sm mx-auto mt-5",
                      alt: "cats",
                      src: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExY2FwamJ4aWhndmx0MW15ejFpN29nY3Q2dmNwMXFpbnRtYmdnbmhreCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/gjC7q8pRQ5jOop8afd/giphy.gif"
                    })
              ]
            });
}

var make = Cats;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
