// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Nullable from "@rescript/core/src/Core__Nullable.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Dog$FancyInput(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("input", {
                      ref: Caml_option.some(props.inputRef),
                      type: "text"
                    }),
                props.children
              ]
            });
}

var FancyInput = {
  make: Dog$FancyInput
};

function Dog(props) {
  var input = React.useRef(null);
  var focusInput = function () {
    Core__Nullable.forEach(input.current, (function (input) {
            input.focus();
          }));
  };
  var onClick = function (param) {
    focusInput();
  };
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(Dog$FancyInput, {
                    children: JsxRuntime.jsx("button", {
                          children: "Click to focus",
                          onClick: onClick
                        }),
                    inputRef: input
                  })
            });
}

var make = Dog;

export {
  FancyInput ,
  make ,
}
/* react Not a pure module */
