// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function FancyButton(props) {
  return JsxRuntime.jsx("button", {
              children: props.children,
              className: "FancyButton"
            });
}

var make = FancyButton;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
