// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function Input(props) {
  var match = React.useState(function () {
        return "";
      });
  var setFname = match[1];
  var onChange = function (evt) {
    evt.preventDefault();
    var value = evt.target.value;
    setFname(function (_prev) {
          return value;
        });
  };
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("input", {
                    value: match[0],
                    onChange: onChange
                  })
            });
}

var make = Input;

export {
  make ,
}
/* react Not a pure module */
