// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function Nav(props) {
  var handleClick = React.useCallback((function (path) {
          RescriptReactRouter.push(path);
        }), []);
  return JsxRuntime.jsxs("nav", {
              children: [
                JsxRuntime.jsx("button", {
                      children: "cat",
                      className: "bg-blue-300 hover:bg-stone-500 p-2 mx-1 rounded text-white",
                      onClick: (function (param) {
                          handleClick("cat");
                        })
                    }),
                JsxRuntime.jsx("button", {
                      children: "dog",
                      className: "bg-blue-300 p-2 mx-1 rounded text-white",
                      onClick: (function (param) {
                          handleClick("dog");
                        })
                    }),
                JsxRuntime.jsx("button", {
                      children: "cats",
                      className: "bg-blue-300 p-2 mx-1 rounded text-white",
                      onClick: (function (param) {
                          handleClick("cats");
                        })
                    }),
                JsxRuntime.jsx("button", {
                      children: "todo",
                      className: "bg-blue-300 p-2 mx-1 rounded text-white",
                      onClick: (function (param) {
                          handleClick("todohome");
                        })
                    }),
                JsxRuntime.jsx("button", {
                      children: "Person",
                      className: "bg-blue-300 p-2 mx-1 rounded text-white",
                      onClick: (function (param) {
                          handleClick("person");
                        })
                    })
              ],
              className: "flex justify-center space-x-2 w-full max-auto"
            });
}

var make = Nav;

export {
  make ,
}
/* react Not a pure module */
