// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as UserProfile from "./UserProfile.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Person(props) {
  var match = React.useState(function () {
        return "";
      });
  var setUserName = match[1];
  var userName = match[0];
  var match$1 = React.useState(function () {
        return 0;
      });
  var setUserAge = match$1[1];
  var userAge = match$1[0];
  var handleNameChange = function ($$event) {
    var value = $$event.target.value;
    setUserName(function (param) {
          return value;
        });
  };
  var handleAgeChange = function ($$event) {
    var value = $$event.target.value;
    var age = Belt_Int.fromString(value);
    if (age !== undefined) {
      return setUserAge(function (param) {
                  return age;
                });
    }
    
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("label", {
                      children: [
                        "Name: ",
                        JsxRuntime.jsx("input", {
                              type: "text",
                              value: userName,
                              onChange: handleNameChange
                            })
                      ]
                    }),
                JsxRuntime.jsx("br", {}),
                JsxRuntime.jsxs("label", {
                      children: [
                        "Age: ",
                        JsxRuntime.jsx("input", {
                              type: "number",
                              value: String(userAge),
                              onChange: handleAgeChange
                            })
                      ]
                    }),
                JsxRuntime.jsx(UserProfile.make, {
                      name: userName,
                      age: userAge
                    })
              ]
            });
}

var make = Person;

export {
  make ,
}
/* react Not a pure module */
