// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function TodoList(props) {
  var onToggle = props.onToggle;
  var onRemove = props.onRemove;
  var todoItems = Belt_Array.map(props.todos, (function (todo) {
          return JsxRuntime.jsxs("li", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                todo.content,
                                JsxRuntime.jsx("div", {
                                      children: todo.detail
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: "Date: " + todo.date
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: "Time: " + todo.time
                                    })
                              ]
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Remove",
                              onClick: (function (param) {
                                  onRemove(todo.id);
                                })
                            }),
                        JsxRuntime.jsx("input", {
                              checked: todo.completed,
                              type: "checkbox",
                              onChange: (function (param) {
                                  onToggle(todo.id);
                                })
                            })
                      ]
                    }, todo.id.toString());
        }));
  return JsxRuntime.jsx("ul", {
              children: todoItems
            });
}

var make = TodoList;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
