// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function TodoForm(props) {
  var onAdd = props.onAdd;
  var match = React.useState(function () {
        return "";
      });
  var setText = match[1];
  var text = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setDetail = match$1[1];
  var detail = match$1[0];
  var match$2 = React.useState(function () {
        return "";
      });
  var setDate = match$2[1];
  var date = match$2[0];
  var match$3 = React.useState(function () {
        return "";
      });
  var setTime = match$3[1];
  var time = match$3[0];
  var handleAddClick = function (param) {
    if (text !== "" && detail !== "") {
      onAdd(text, detail, date, time);
      setText(function (param) {
            return "";
          });
      setDetail(function (param) {
            return "";
          });
      setDate(function (param) {
            return "";
          });
      return setTime(function (param) {
                  return "";
                });
    }
    
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("label", {
                      children: [
                        "Name: ",
                        JsxRuntime.jsx("input", {
                              placeholder: "Enter new todo",
                              type: "text",
                              value: text,
                              onChange: (function ($$event) {
                                  setText($$event.target.value);
                                })
                            })
                      ]
                    }),
                JsxRuntime.jsxs("label", {
                      children: [
                        "Detail: ",
                        JsxRuntime.jsx("input", {
                              placeholder: "Enter todo detail",
                              type: "text",
                              value: detail,
                              onChange: (function ($$event) {
                                  setDetail($$event.target.value);
                                })
                            })
                      ]
                    }),
                JsxRuntime.jsxs("label", {
                      children: [
                        "Date: ",
                        JsxRuntime.jsx("input", {
                              type: "date",
                              value: date,
                              onChange: (function ($$event) {
                                  setDate($$event.target.value);
                                })
                            })
                      ]
                    }),
                JsxRuntime.jsxs("label", {
                      children: [
                        "Time: ",
                        JsxRuntime.jsx("input", {
                              type: "time",
                              value: time,
                              onChange: (function ($$event) {
                                  setTime($$event.target.value);
                                })
                            })
                      ]
                    }),
                JsxRuntime.jsx("button", {
                      children: "Add Todo",
                      disabled: text === "" || detail === "",
                      onClick: handleAddClick
                    })
              ]
            });
}

var make = TodoForm;

export {
  make ,
}
/* react Not a pure module */
