// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function UserProfile(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "User Profile"
                    }),
                JsxRuntime.jsx("p", {
                      children: "Name:" + props.name
                    }),
                JsxRuntime.jsx("p", {
                      children: "Age:" + String(props.age)
                    })
              ]
            });
}

var make = UserProfile;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
