// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nav from "./Components/Nav.res.mjs";
import * as Input from "./Components/Input.res.mjs";
import * as Pages from "./Pages.res.mjs";
import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function App(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  React.useEffect((function () {
          var match = url.path;
          if (match) {
            
          } else {
            RescriptReactRouter.replace("cat");
          }
        }), []);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Cats or Dogs or Cat",
                      className: "text-3xl m-5 justify-center text-center "
                    }),
                JsxRuntime.jsx(Nav.make, {}),
                JsxRuntime.jsx(Input.make, {}),
                JsxRuntime.jsx(Pages.make, {})
              ],
              className: " justify-center text-2xl min-h-screen p-5 text-gray-700"
            });
}

var make = App;

export {
  make ,
}
/* Nav Not a pure module */
