// Generated by ReScript, PLEASE EDIT WITH CARE


function storeValue(key, value) {
  localStorage.setItem(key, value);
}

function getValue(key) {
  var value = localStorage.getItem(key);
  if (value == null) {
    return "Default Value";
  } else {
    return value;
  }
}

export {
  storeValue ,
  getValue ,
}
/* No side effect */
