// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cat from "./Components/Cat.res.mjs";
import * as Dog from "./Components/Dog.res.mjs";
import * as Cats from "./Components/Cats.res.mjs";
import * as Person from "./Components/Person.res.mjs";
import * as TodoHome from "./Components/TodoHome.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function Pages(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (match) {
    switch (match.hd) {
      case "cat" :
          if (!match.tl) {
            return JsxRuntime.jsx(Cat.make, {});
          }
          break;
      case "cats" :
          if (!match.tl) {
            return JsxRuntime.jsx(Cats.make, {});
          }
          break;
      case "dog" :
          if (!match.tl) {
            return JsxRuntime.jsx(Dog.make, {});
          }
          break;
      case "person" :
          if (!match.tl) {
            return JsxRuntime.jsx(Person.make, {});
          }
          break;
      case "todohome" :
          if (!match.tl) {
            return JsxRuntime.jsx(TodoHome.make, {});
          }
          break;
      default:
        
    }
  }
  return JsxRuntime.jsx("h2", {
              children: "404: page not found"
            });
}

var make = Pages;

export {
  make ,
}
/* Cat Not a pure module */
